using Aisd_tree;
Tree tree = new Tree();
tree.AddNode(8);
tree.AddNode(3);
tree.AddNode(10);
tree.AddNode(1);
tree.AddNode(6);
tree.AddNode(14);
tree.AddNode(4);
tree.AddNode(7);
tree.AddNode(13);
tree.RemoveWithTwoChildren(6);
Console.WriteLine(tree.root.left.right.data);
